apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus           # 与 rules.yaml 中 datasourceUid 对齐
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    uid: loki                 # 与 rules.yaml 中 datasourceUid 对齐
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
